import tseslint from "typescript-eslint";
import caracal from "@caracal-lynx/eslint-config";

// docs-site was unlinted until DAG-242: 443 lines across four files, covered by
// no eslint config and no lint job. The one defect found in them was found by
// CodeQL, not ESLint (js/incomplete-sanitization in the Markdown table builder,
// sluice#29 / alert 2 on the public mirror).
//
// packages/sluice/eslint.config.js deliberately IGNORES this directory — that
// ignore stays. It exists so a stray .ts here cannot break sluice's own
// pre-commit hook, and this package now has its own config and its own
// lefthook job.
//
// The shared config is type-aware via `projectService`, and tsconfig.json here
// covers `**/*`, so scripts/*.ts lint with type information. `astro.config.mjs`
// and `src/content.config.ts` fall into the shared config's
// `disableTypeChecked` block (`**/*.{js,mjs,cjs}` and `**/*.config.ts`) — that
// is what stops the parser erroring on files outside a TS project, and it is
// the same mechanism DAG-208 added for the rest of the fleet.
export default tseslint.config(...caracal, {
  // `.astro/` is generated by `astro sync` / `astro build` and gitignored;
  // `dist/` is build output. Neither is ours to lint. The shared config already
  // ignores dist, coverage and node_modules — `.astro` is the local addition.
  ignores: [".astro/**"],
});
