pipeline:
  name: hello-world
  client: demo
  version: "1.0"
  entity: Customer

source:
  adapter: csv
  file: ./examples/data/hello-world.csv

dq:
  rules:
    - field: email
      checks:
        - { type: notNull, severity: critical }
        - { type: email, severity: warning }

transform:
  fields:
    - { from: name, to: Name, type: string, cleanse: trim }
    - { from: email, to: Email, type: string, cleanse: trim|lowercase }
    - { from: country, to: Country, type: string, default: GB }

target:
  adapter: csv
  output: ./output/hello-world-clean.csv
