/* eslint-disable no-console */
/**
 * Sync the repo-root CHANGELOG.md (Changesets-managed) into the docs site
 * as src/content/docs/changelog.md, prepending Starlight frontmatter.
 *
 * The destination file is gitignored is wholly regenerated on every run, so
 * never hand-edit it.
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SOURCE = join(__dirname, '..', '..', 'CHANGELOG.md');
const OUTPUT = join(__dirname, '..', 'src', 'content', 'docs', 'changelog.md');

const FRONTMATTER = `---
title: Changelog
description: Release history for the @caracal-lynx/sluice npm package.
---

<!--
  AUTO-GENERATED FILE.
  Synced from /CHANGELOG.md by docs-site/scripts/sync-changelog.ts.
  Do not hand-edit; the canonical source is the repo-root CHANGELOG.md
  (which itself is generated by Changesets).
-->

`;

const raw = readFileSync(SOURCE, 'utf-8');

// Strip the Changesets-emitted top-level heading "# @caracal-lynx/sluice" —
// Starlight already shows the page title from the frontmatter.
const stripped = raw.replace(/^#\s+@caracal-lynx\/sluice\s*\n+/m, '');

mkdirSync(dirname(OUTPUT), { recursive: true });
writeFileSync(OUTPUT, FRONTMATTER + stripped, 'utf-8');
console.log(`✓ Synced CHANGELOG.md → ${OUTPUT}`);
